#!/usr/bin/env python3
"""Write data/scholar.json into index.html.

  * the h-index, Citations and Publications figures in the metrics row
  * the "synced from Google Scholar on …" date in the footer
  * Scholar papers that are not yet on the page, sorted into journal,
    conference or book chapter from their venue, between the
    SCHOLAR-ADDED markers in PUBS

Hand-written PUBS entries are never changed: a paper already on the page
keeps its curated authors, venue, tags and DOI. The block between the markers
is rewritten on every run, so move an entry above the markers to curate it.

Prints what it could not place, so the workflow log says what needs a look.
"""
import difflib
import html
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / 'index.html'
DATA = ROOT / 'data' / 'scholar.json'
START = '  // >>> SCHOLAR-ADDED: generated by scripts/scholar_apply.py; edits here are overwritten\n'
END = '  // <<< SCHOLAR-ADDED\n'
ME = re.compile(r'\b(H\.?\s*|Himanshu\s+)Verma\b', re.I)

CONF = re.compile(r'conference|conf\.|symposium|proceedings|workshop|congress|\bicc|\bieee .*\(', re.I)


def norm(t):
    return re.sub(r'[^a-z0-9]+', ' ', html.unescape(t).lower()).strip()


def same(a, b):
    a, b = norm(a), norm(b)
    return a == b or (min(len(a), len(b)) > 30 and (a in b or b in a)) or \
        difflib.SequenceMatcher(None, a, b).ratio() >= 0.88


def classify(p):
    """journal | conference | chapter, or None when the venue doesn't say."""
    f = p.get('fields', {})
    if 'Patent office' in f or 'Patent number' in f:
        return None
    if 'Conference' in f:
        return 'conference'
    if 'Book' in f:
        return 'conference' if CONF.search(f['Book']) else 'chapter'
    if re.search(r'arxiv|ssrn|research square|preprint|techrxiv',
                 ' '.join(f.values()) + p.get('venue_line', ''), re.I):
        return None
    journal = f.get('Journal') or f.get('Source')
    if journal:
        return 'conference' if CONF.search(journal) else 'journal'
    if CONF.search(p.get('venue_line', '')):
        return 'conference'
    return None


def js(s):
    return s.replace('\\', '\\\\').replace("'", "\\'")


def ent(s):
    return html.escape(s, quote=False)


def initials(name):
    parts = name.split()
    return ' '.join([w[0] + '.' for w in parts[:-1]] + parts[-1:]) if len(parts) > 1 else name


def entry(p, kind):
    f = p.get('fields', {})
    au = ', '.join(initials(a.strip()) for a in (f.get('Authors') or p['authors']).split(','))
    au = ME.sub(lambda m: '*' + m.group(0) + '*', au, count=1)
    name = f.get('Journal') or f.get('Source') or f.get('Conference') or f.get('Book') or p.get('venue_line', '')
    ve = '<em>' + ent(name) + '</em>' if kind == 'journal' else \
        'in <em>' + ent(name) + '</em>' if kind == 'chapter' else ent(name)
    extra = [ent(f['Publisher'])] if f.get('Publisher') and f['Publisher'].lower() not in name.lower() else []
    if f.get('Volume'):
        extra.append('vol. ' + ent(f['Volume']))
    if f.get('Issue'):
        extra.append('no. ' + ent(f['Issue']))
    if f.get('Pages'):
        extra.append('pp. ' + ent(f['Pages'].replace('-', '–')))
    ve = ', '.join([ve] + extra)
    out = "  { type:'%s', year:%s, title:'%s',\n    au:'%s', ve:'%s', tags:[]" % (
        kind, p['year'] or "''", js(p['title']), js(au), js(ve))
    doi = re.search(r'\b(10\.\d{4,9}/[^\s&?#]+)', p.get('link') or '')
    if doi:
        out += ", doi:'https://doi.org/%s'" % js(doi.group(1))
    return out + ' },\n'


def main():
    d = json.loads(DATA.read_text())
    page = PAGE.read_text()

    page = re.sub(r'(<span class="n">)\d+(</span><span class="l">h-index</span>)',
                  r'\g<1>%d\2' % d['h_index'], page)
    page = re.sub(r'(<span class="n">)\d+(</span><span class="l">Citations</span>)',
                  r'\g<1>%d\2' % d['citations'], page)
    when = date.fromisoformat(d['fetched'])
    page = re.sub(r'(<span id="scholar-date">).*?(</span>)',
                  r'\g<1>%d %s\2' % (when.day, when.strftime('%B %Y')), page)

    head, rest = page.split('const PUBS = [\n', 1)
    body, tail = rest.split('\n];', 1)
    body += '\n'
    if START in body:
        before, after = body.split(START, 1)
        curated = before + after.split(END, 1)[1]
    else:
        curated = body
    curated = curated.rstrip().rstrip(',')
    titles = re.findall(r"title:'((?:[^'\\]|\\.)*)'", curated)
    types = re.findall(r"type:'(\w+)'", curated)

    added, skipped, review_hits = [], [], []
    for p in d['publications']:
        hit = next((i for i, t in enumerate(titles) if same(t.replace("\\'", "'"), p['title'])), None)
        if hit is not None:
            if types[hit] == 'review':
                review_hits.append(p['title'])
            continue
        kind = classify(p)
        if kind:
            added.append(entry(p, kind))
        else:
            skipped.append(p)
    missing = [t for t, k in zip(titles, types) if k != 'review'
               and not any(same(t.replace("\\'", "'"), p['title']) for p in d['publications'])]

    # Array literals allow a trailing comma, so every generated entry ends in one.
    page = head + 'const PUBS = [\n' + curated + ',\n\n' + START + ''.join(added) + END + '];' + tail

    published = len([k for k in types if k != 'review']) + len(added)
    page = re.sub(r'(<span class="n">)\d+(</span><span class="l">Publications</span>)',
                  r'\g<1>%d\2' % published, page)
    PAGE.write_text(page)

    print(f"Citations {d['citations']}, h-index {d['h_index']}, {published} publications on the page")
    print(f'Added from Scholar: {len(added)}')
    for p in skipped:
        print(f"  not placed (venue unclear): {p['title']} | {p.get('venue_line', '')}")
    for t in review_hits:
        print(f'  marked under review on the page but listed on Scholar: {t}')
    for t in missing:
        print(f'  on the page but not found on Scholar: {t}')


if __name__ == '__main__':
    sys.exit(main())
